In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.1'

In [6]:
x = tf.random.normal(shape=[3,4], mean=0, stddev=1)

In [7]:
x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.11663698, -0.2287391 ,  1.7170587 ,  0.45601994],
       [ 0.37789315,  0.19809559,  1.1231546 , -0.4747577 ],
       [ 0.0428953 , -0.49812612, -0.01854416, -0.5067394 ]],
      dtype=float32)>

In [11]:
A = tf.reshape(tf.constant(range(3)), (3,1))
B = tf.reshape(tf.constant(range(2)), (1,2))
A, B

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [12]:
B

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>