In [29]:
import tensorflow as tf

from math import sqrt

try:
    tf.contrib.eager.enable_eager_execution()
except ValueError:
    pass  # enable_eager_execution errors after its first call

In [30]:
tensor = tf.constant('Hello, world!')
print(tensor)
print(type(tensor))
tensor_value = tensor.numpy()
print(tensor_value)
print(type(tensor_value))

tf.Tensor(b'Hello, world!', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>
b'Hello, world!'
<class 'bytes'>


In [31]:
cl = [256, 7, 3]
stdv = 1 / sqrt(cl[0] * cl[1])
W = tf.Variable(tf.random_uniform([7, 69, 1, 256], minval=-stdv, maxval=stdv), dtype='float32', name='W')
W = W.numpy()

In [32]:
W.shape

(7, 69, 1, 256)

In [34]:
W[0]

array([[[-0.01329625, -0.02075823, -0.01688867, ...,  0.01085667,
          0.02011919,  0.00861265]],

       [[ 0.00668623, -0.00011059,  0.01303988, ...,  0.00939691,
         -0.02094685,  0.02237237]],

       [[-0.01806926,  0.00563697,  0.00037693, ..., -0.02295386,
          0.01061822, -0.00096934]],

       ...,

       [[-0.00118052, -0.00791057, -0.01977578, ...,  0.01149489,
          0.01577958,  0.01678179]],

       [[-0.00562945, -0.0021513 ,  0.02042801, ..., -0.00728504,
          0.01520394, -0.01632841]],

       [[-0.00122328,  0.00469836,  0.01094379, ..., -0.00810773,
         -0.00190229, -0.0232883 ]]], dtype=float32)

In [6]:
W[0][0]

array([[ 0.49164343, -0.7574632 ,  0.25555873, -0.39000797,  0.96162915,
        -0.22404861,  0.5087216 ,  0.99826884, -0.9389212 , -0.4840939 ,
        -0.31122875,  0.9244697 , -0.01815057, -0.7254896 , -0.9322963 ,
         0.41646457,  0.89918995, -0.85320497,  0.00272608, -0.9200599 ,
        -0.3416283 , -0.47995162,  0.8807969 , -0.779202  ,  0.7091472 ,
        -0.7360158 , -0.497818  ,  0.8114648 , -0.91600156,  0.33176112,
        -0.03045964,  0.21153712,  0.03069711,  0.9941683 ,  0.2846625 ,
         0.19968319,  0.5673795 ,  0.32327724,  0.17766356, -0.00604391,
         0.9949267 ,  0.9875195 , -0.32566047, -0.9980433 ,  0.09389997,
        -0.7172923 ,  0.45769787,  0.2391243 ,  0.14528155,  0.81573796,
        -0.12964797, -0.17782259,  0.7347727 , -0.54326963, -0.23226643,
         0.25948143, -0.8931663 ,  0.37890077, -0.91854477,  0.2839532 ,
         0.07348061, -0.31273222, -0.3222077 ,  0.42702532, -0.3251412 ,
        -0.13216686, -0.780602  ,  0.44163036,  0.2

In [7]:
import numpy as np

In [8]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [10]:
x.transpose([1, 0])

array([[1, 3],
       [2, 4]])

In [14]:
x = [[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[9,12,13,14],[15,16,17,18],[5,6,7,8]]]

x = np.array(x)
x, x.shape

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 5,  6,  7,  8]],
 
        [[ 9, 12, 13, 14],
         [15, 16, 17, 18],
         [ 5,  6,  7,  8]]]), (2, 3, 4))

In [18]:
# 高与行转置
x.transpose([1, 0, 2])
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]],

       [[ 9, 12, 13, 14],
        [15, 16, 17, 18],
        [ 5,  6,  7,  8]]])

In [16]:
x.shape

(2, 3, 4)

In [19]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]],

       [[ 9, 12, 13, 14],
        [15, 16, 17, 18],
        [ 5,  6,  7,  8]]])

In [20]:
tf.transpose(x, perm=[1, 0, 2])

<tf.Tensor: id=22, shape=(3, 2, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 9, 12, 13, 14]],

       [[ 5,  6,  7,  8],
        [15, 16, 17, 18]],

       [[ 5,  6,  7,  8],
        [ 5,  6,  7,  8]]])>

In [21]:
tf.transpose(x, perm=[0, 2, 1])

<tf.Tensor: id=26, shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 1,  5,  5],
        [ 2,  6,  6],
        [ 3,  7,  7],
        [ 4,  8,  8]],

       [[ 9, 15,  5],
        [12, 16,  6],
        [13, 17,  7],
        [14, 18,  8]]])>

In [23]:
y = np.array([x, x, x])
y, y.shape

(array([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 5,  6,  7,  8]],
 
         [[ 9, 12, 13, 14],
          [15, 16, 17, 18],
          [ 5,  6,  7,  8]]],
 
 
        [[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 5,  6,  7,  8]],
 
         [[ 9, 12, 13, 14],
          [15, 16, 17, 18],
          [ 5,  6,  7,  8]]],
 
 
        [[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 5,  6,  7,  8]],
 
         [[ 9, 12, 13, 14],
          [15, 16, 17, 18],
          [ 5,  6,  7,  8]]]]), (3, 2, 3, 4))

In [25]:
y = tf.transpose(y, [0, 1, 3, 2])

In [26]:
y.shape

TensorShape([Dimension(3), Dimension(2), Dimension(4), Dimension(3)])

In [27]:
y

<tf.Tensor: id=32, shape=(3, 2, 4, 3), dtype=int64, numpy=
array([[[[ 1,  5,  5],
         [ 2,  6,  6],
         [ 3,  7,  7],
         [ 4,  8,  8]],

        [[ 9, 15,  5],
         [12, 16,  6],
         [13, 17,  7],
         [14, 18,  8]]],


       [[[ 1,  5,  5],
         [ 2,  6,  6],
         [ 3,  7,  7],
         [ 4,  8,  8]],

        [[ 9, 15,  5],
         [12, 16,  6],
         [13, 17,  7],
         [14, 18,  8]]],


       [[[ 1,  5,  5],
         [ 2,  6,  6],
         [ 3,  7,  7],
         [ 4,  8,  8]],

        [[ 9, 15,  5],
         [12, 16,  6],
         [13, 17,  7],
         [14, 18,  8]]]])>

In [35]:
filter_data = tf.Variable( np.random.rand(4, 4, 2, 3), dtype = np.float32)
filter_data.numpy()

array([[[[0.30799896, 0.82316893, 0.7636575 ],
         [0.6583027 , 0.15469258, 0.71651363]],

        [[0.11923435, 0.38333213, 0.42696455],
         [0.853428  , 0.1045616 , 0.84162444]],

        [[0.7853397 , 0.15419328, 0.7083064 ],
         [0.06169184, 0.13647841, 0.655387  ]],

        [[0.46386954, 0.3069218 , 0.88832426],
         [0.46349984, 0.5227203 , 0.18267062]]],


       [[[0.53514373, 0.44081578, 0.2121148 ],
         [0.6443269 , 0.7175072 , 0.11466067]],

        [[0.518557  , 0.37938312, 0.4196383 ],
         [0.02403331, 0.5753795 , 0.5665819 ]],

        [[0.9579694 , 0.8800726 , 0.65177256],
         [0.01282637, 0.43720058, 0.9960695 ]],

        [[0.17853965, 0.91726494, 0.7515126 ],
         [0.53085244, 0.8674848 , 0.41722327]]],


       [[[0.9125486 , 0.12552531, 0.9561104 ],
         [0.5558525 , 0.7146968 , 0.27074197]],

        [[0.11567192, 0.29358128, 0.65297204],
         [0.87951785, 0.7711498 , 0.01380999]],

        [[0.6780239 , 0.12091808, 0.

In [36]:
x = tf.Variable( np.random.rand(128, 34, 256, 1), dtype = np.float32)
vec_dim = x.get_shape()[1].value * x.get_shape()[2].value
vec_dim

8704

In [37]:
x = tf.reshape(x, [-1, vec_dim])

In [44]:
x

<tf.Tensor: id=73, shape=(128, 8704), dtype=float32, numpy=
array([[0.26091298, 0.02395225, 0.08215548, ..., 0.6024838 , 0.8969037 ,
        0.0055272 ],
       [0.8848222 , 0.65228057, 0.76696676, ..., 0.60426486, 0.81016   ,
        0.9583514 ],
       [0.48387542, 0.53225696, 0.26299882, ..., 0.8052586 , 0.5187682 ,
        0.10895912],
       ...,
       [0.8247141 , 0.79134506, 0.28942916, ..., 0.1947049 , 0.72582   ,
        0.6570907 ],
       [0.50457525, 0.9717265 , 0.41672745, ..., 0.07750852, 0.55426055,
        0.344219  ],
       [0.09515209, 0.35281268, 0.00765212, ..., 0.92056334, 0.26688537,
        0.8610988 ]], dtype=float32)>

In [40]:
x.shape

TensorShape([Dimension(128), Dimension(8704)])

In [41]:
a = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

<tf.Variable 'Variable:0' shape=(9,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [45]:
b = tf.Variable(tf.random_uniform(shape=[cl[0]], minval=-stdv, maxval=stdv),
                                name='b')

In [47]:
b.shape

TensorShape([Dimension(256)])

In [48]:
fully_layers=[1024, 1024]
weights = [vec_dim] + list(fully_layers)
weights

[8704, 1024, 1024]

In [74]:
stdv = 1 / sqrt(weights[0])
fl = 1024
W = tf.Variable(tf.random_uniform([weights[0], fl], minval=-stdv, maxval=stdv), dtype='float32',
                                name='W')
b = tf.Variable(tf.random_uniform(shape=[fl], minval=-stdv, maxval=stdv), dtype='float32', name='b')

In [75]:
len(W.numpy())

8704

In [76]:
X = tf.Variable( np.random.rand(128, 8704), dtype = np.float32)
X

<tf.Variable 'Variable:0' shape=(128, 8704) dtype=float32, numpy=
array([[0.2901108 , 0.83291554, 0.6619928 , ..., 0.09755427, 0.91522104,
        0.4779632 ],
       [0.37430683, 0.31983247, 0.07438554, ..., 0.51613784, 0.68596303,
        0.37781325],
       [0.27670228, 0.5220767 , 0.5729016 , ..., 0.9040989 , 0.19318445,
        0.12245632],
       ...,
       [0.16640432, 0.68992054, 0.751674  , ..., 0.28412947, 0.6025982 ,
        0.76797074],
       [0.26716244, 0.04463526, 0.04058908, ..., 0.29468137, 0.65247977,
        0.42201507],
       [0.49368113, 0.46398333, 0.4197654 , ..., 0.10489789, 0.295936  ,
        0.00209406]], dtype=float32)>

In [77]:
x = tf.nn.xw_plus_b(X, W, b)

In [78]:
x

<tf.Tensor: id=275, shape=(128, 1024), dtype=float32, numpy=
array([[ 0.13036233, -0.06408401, -0.551159  , ..., -0.21135771,
         0.3154488 , -0.00207749],
       [ 0.20575093, -0.19009405, -0.32586235, ..., -0.4198727 ,
         0.32316473,  0.28090763],
       [ 0.29095927, -0.25047466, -0.33680832, ..., -0.50708663,
         0.24769714,  0.22998542],
       ...,
       [ 0.30271298, -0.2856101 , -0.8030951 , ..., -0.47145957,
         0.37966487, -0.06391963],
       [ 0.26938105, -0.36993653, -0.36297214, ..., -0.4588333 ,
         0.7534444 , -0.00255142],
       [ 0.2885882 , -0.6012203 , -0.7255537 , ..., -0.5013625 ,
         0.6659295 ,  0.37876338]], dtype=float32)>

In [62]:
b

<tf.Variable 'b:0' shape=(1024,) dtype=float32, numpy=
array([ 0.00465211,  0.00034995, -0.00761652, ...,  0.0064838 ,
        0.00998234,  0.0100738 ], dtype=float32)>

In [63]:

x1=[[1, 2, 3],[4, 5, 6]]
w1=[[ 7,  8],[ 9, 10],[11, 12]]

np.dot(x1,w1)


array([[ 58,  64],
       [139, 154]])

In [69]:
import tensorflow as tf
x=[[1, 2, 3],[4, 5, 6]]
w=[[ 7,  8],[ 9, 10],[11, 12]]
b=[[3,3],[3,3]]
result=tf.nn.xw_plus_b(x,w,[1,1])
result

<tf.Tensor: id=194, shape=(2, 2), dtype=int32, numpy=
array([[ 59,  65],
       [140, 155]], dtype=int32)>

In [82]:
stdv = 1 / sqrt(weights[1])
fl = 1024
W = tf.Variable(tf.random_uniform([weights[1], fl], minval=-stdv, maxval=stdv), dtype='float32',
                                name='W')
b = tf.Variable(tf.random_uniform(shape=[fl], minval=-stdv, maxval=stdv), dtype='float32', name='b')

In [72]:
b

<tf.Variable 'b:0' shape=(1024,) dtype=float32, numpy=
array([-0.01755464, -0.02979476,  0.02828516, ..., -0.01914884,
       -0.01361658,  0.02022907], dtype=float32)>

In [80]:
x

<tf.Tensor: id=275, shape=(128, 1024), dtype=float32, numpy=
array([[ 0.13036233, -0.06408401, -0.551159  , ..., -0.21135771,
         0.3154488 , -0.00207749],
       [ 0.20575093, -0.19009405, -0.32586235, ..., -0.4198727 ,
         0.32316473,  0.28090763],
       [ 0.29095927, -0.25047466, -0.33680832, ..., -0.50708663,
         0.24769714,  0.22998542],
       ...,
       [ 0.30271298, -0.2856101 , -0.8030951 , ..., -0.47145957,
         0.37966487, -0.06391963],
       [ 0.26938105, -0.36993653, -0.36297214, ..., -0.4588333 ,
         0.7534444 , -0.00255142],
       [ 0.2885882 , -0.6012203 , -0.7255537 , ..., -0.5013625 ,
         0.6659295 ,  0.37876338]], dtype=float32)>

In [83]:
x = tf.nn.xw_plus_b(x, W, b)

In [84]:
x

<tf.Tensor: id=313, shape=(128, 1024), dtype=float32, numpy=
array([[-0.09975816,  0.2893965 , -0.02795241, ...,  0.19764054,
         0.05368655, -0.00926338],
       [-0.11563069,  0.35026807, -0.12495884, ..., -0.06432645,
         0.24929076, -0.07218348],
       [-0.1152805 ,  0.27792373, -0.09132429, ...,  0.0041832 ,
        -0.00885827, -0.02416847],
       ...,
       [-0.21786502,  0.46398368, -0.0934715 , ...,  0.04117008,
         0.02778594,  0.0232548 ],
       [-0.10884545,  0.4512498 , -0.08760331, ...,  0.23547985,
         0.07294088, -0.09993291],
       [-0.10058627,  0.3406928 ,  0.12559593, ...,  0.09196529,
         0.07933102, -0.04062647]], dtype=float32)>

In [86]:
x = tf.nn.dropout(x, 0.9)

In [87]:
x

<tf.Tensor: id=327, shape=(128, 1024), dtype=float32, numpy=
array([[-0.11084241,  0.32155168, -0.03105824, ...,  0.2196006 ,
         0.        , -0.01029265],
       [-0.12847856,  0.38918674, -0.13884316, ..., -0.07147384,
         0.27698976, -0.08020387],
       [-0.12808944,  0.30880415, -0.        , ...,  0.004648  ,
        -0.00984252, -0.02685385],
       ...,
       [-0.24207225,  0.51553744, -0.10385722, ...,  0.04574453,
         0.03087327,  0.02583867],
       [-0.12093939,  0.50138867, -0.09733701, ...,  0.26164427,
         0.08104543, -0.11103657],
       [-0.        ,  0.37854755,  0.13955103, ...,  0.10218365,
         0.08814558, -0.04514053]], dtype=float32)>

In [90]:
num_of_classes= 4
stdv = 1 / sqrt(weights[-1])
# 输出层
W = tf.Variable(tf.random_uniform([weights[-1], num_of_classes], minval=-stdv, maxval=stdv),
                            dtype='float32',
                            name='W')
b = tf.Variable(tf.random_uniform(shape=[num_of_classes], minval=-stdv, maxval=stdv), name='b')

p_y_given_x = tf.nn.xw_plus_b(x, W, b, name="scores")
predictions = tf.argmax(p_y_given_x, 1)

In [93]:
p_y_given_x.shape

TensorShape([Dimension(128), Dimension(4)])

In [94]:
predictions

<tf.Tensor: id=362, shape=(128,), dtype=int64, numpy=
array([0, 0, 1, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 0,
       3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 1, 3,
       0, 3, 3, 3, 3, 0, 0, 3, 0, 3, 0, 3, 3, 3, 0, 0, 3, 0, 0, 0, 3, 3,
       3, 3, 2, 0, 0, 0, 3, 0, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 0, 0, 3,
       3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3])>